export const restaurantData = [
  {
    cardType: "seeAllRestaurants",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "seeAllRestaurants",
      data: {
        title: "SEE ALL",
        totalOpenRestaurants: 17,
        cards: [
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "100222",
              name: "Shreelal Food Plaza",
              uuid: "f39c5bad-c6b8-4022-a9f5-accdebc40460",
              city: "57",
              area: "Khandagiri",
              totalRatingsString: "10000+ ratings",
              cloudinaryImageId: "oycvffrrb3oyp2ncyn1n",
              cuisines: ["Indian", "Chinese", "Sweets"],
              tags: [],
              costForTwo: 20000,
              costForTwoString: "₹200 FOR TWO",
              deliveryTime: 27,
              minDeliveryTime: 27,
              maxDeliveryTime: 27,
              slaString: "27 MINS",
              lastMileTravel: 3,
              slugs: {
                restaurant: "shreelal-food-plaza-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address: "95/2472 Jain Temple Road, Khandagiri, Bhubaneshwar",
              locality: "Jain Temple Road",
              parentId: 185997,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2700,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2700,
                message: "",
                title: "Delivery Charge",
                amount: "2700",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "3 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "15% OFF",
                subHeader: "ABOVE ₹350",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "100222",
                deliveryTime: 27,
                minDeliveryTime: 27,
                maxDeliveryTime: 27,
                lastMileTravel: 3,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "3.9",
              totalRatings: 10000,
              new: false,
            },
            subtype: "basic",
            scrubber: {
              value: "27 MINS",
            },
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "135956",
              name: "Maharaja Ganguram",
              uuid: "952336a2-97cd-4778-acff-62af775c6066",
              city: "57",
              area: "Baramunda",
              totalRatingsString: "5000+ ratings",
              cloudinaryImageId: "qtvveopbwpczdniuglu1",
              cuisines: ["Sweets"],
              tags: [],
              costForTwo: 10000,
              costForTwoString: "₹100 FOR TWO",
              deliveryTime: 31,
              minDeliveryTime: 31,
              maxDeliveryTime: 31,
              slaString: "31 MINS",
              lastMileTravel: 6.5,
              slugs: {
                restaurant: "maharaja-ganguram-baramunda-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "MIG- 30, Baramunda Housing Board Colony, Baramunda, Bhubaneshwar",
              locality: "Housing Board Colony",
              parentId: 129876,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              ribbon: [
                {
                  type: "PROMOTED",
                },
              ],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 4200,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 4200,
                message: "",
                title: "Delivery Charge",
                amount: "4200",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID:
                "cid=7221829~p=4~eid=00000189-1467-4801-2668-e6ab002a044e~srvts=1688264460289",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "6.5 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "₹75 OFF",
                subHeader: "ABOVE ₹199",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "135956",
                deliveryTime: 31,
                minDeliveryTime: 31,
                maxDeliveryTime: 31,
                lastMileTravel: 6.5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: true,
              avgRating: "4.1",
              totalRatings: 5000,
              new: false,
            },
            subtype: "basic",
            scrubber: {
              value: "31 MINS",
            },
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "488712",
              name: "Satya Tiffin Stall",
              uuid: "f6da2929-b24c-44f0-8488-49884df04af4",
              city: "57",
              area: "Khandagiri",
              totalRatingsString: "Too Few Ratings",
              cloudinaryImageId: "mumfvz2rauv5hdq6lbqc",
              cuisines: ["Fast Food", "Snacks"],
              tags: [],
              costForTwo: 15000,
              costForTwoString: "₹150 FOR TWO",
              deliveryTime: 31,
              minDeliveryTime: 31,
              maxDeliveryTime: 31,
              slaString: "31 MINS",
              lastMileTravel: 5,
              slugs: {
                restaurant: "satya-tiffin-stall-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "Dumduma, Dumduma PH-I, PH-II, PH-IV, PH-V, Ward 65, BHUBANESWAR MUNICIPAL CORPORATION, Orissa - 751019",
              locality: "Dumduma",
              parentId: 293506,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 3700,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 3700,
                message: "",
                title: "Delivery Charge",
                amount: "3700",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "5 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "30% OFF",
                subHeader: "UPTO ₹75",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "488712",
                deliveryTime: 31,
                minDeliveryTime: 31,
                maxDeliveryTime: 31,
                lastMileTravel: 5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "--",
              totalRatings: 0,
              new: false,
            },
            subtype: "basic",
            scrubber: {
              value: "31 MINS",
            },
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "294096",
              name: "Atma Ganguram Sweets",
              uuid: "5635e9c0-658e-4afe-8558-8690148ba366",
              city: "57",
              area: "Nayapalli",
              totalRatingsString: "1000+ ratings",
              cloudinaryImageId: "iu3p2q2pcarql7mw2ynj",
              cuisines: ["Snacks", "Sweets"],
              tags: [],
              costForTwo: 30000,
              costForTwoString: "₹300 FOR TWO",
              deliveryTime: 31,
              minDeliveryTime: 31,
              maxDeliveryTime: 31,
              slaString: "31 MINS",
              lastMileTravel: 7.800000190734863,
              slugs: {
                restaurant: "atma-ganguram-sweets-sahid-nagar-sahid-nagar",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "PLOT NO. N 1/40, IRC VILLAGE, NAYAPALLI, WARD 25, BHUBANESWAR-751015",
              locality: "Irc Village",
              parentId: 37624,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 4700,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 4700,
                message: "",
                title: "Delivery Charge",
                amount: "4700",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "7.8 kms",
              hasSurge: false,
              sla: {
                restaurantId: "294096",
                deliveryTime: 31,
                minDeliveryTime: 31,
                maxDeliveryTime: 31,
                lastMileTravel: 7.800000190734863,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.1",
              totalRatings: 1000,
              new: false,
            },
            subtype: "basic",
            scrubber: {
              value: "31 MINS",
            },
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "391993",
              name: "Function Junction Cake More",
              uuid: "d1c58e0d-c72f-49b2-b406-362fd7fe8836",
              city: "57",
              area: "Baramunda",
              totalRatingsString: "100+ ratings",
              cloudinaryImageId: "8899a77410deaa9a38b11b69c23a909d",
              cuisines: ["Bakery", "Desserts"],
              tags: [],
              costForTwo: 20000,
              costForTwoString: "₹200 FOR TWO",
              deliveryTime: 32,
              minDeliveryTime: 32,
              maxDeliveryTime: 32,
              slaString: "32 MINS",
              lastMileTravel: 5.800000190734863,
              slugs: {
                restaurant: "function-junction-cake-more-old-bbsr-old-bbsr",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "Plot No -253,Baramuda village,ward no 50 Bubaneshwar Municipal corporation 751003",
              locality: "Baramuda village",
              parentId: 245919,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 3700,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 3700,
                message: "",
                title: "Delivery Charge",
                amount: "3700",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "5.8 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "₹100 OFF",
                subHeader: "ABOVE ₹349",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "391993",
                deliveryTime: 32,
                minDeliveryTime: 32,
                maxDeliveryTime: 32,
                lastMileTravel: 5.800000190734863,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.1",
              totalRatings: 100,
              new: false,
            },
            subtype: "basic",
            scrubber: {
              value: "32 MINS",
            },
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "375559",
              name: "Priya Restaurant",
              uuid: "ef31533b-7cb4-468e-a149-45ac0fd0d4aa",
              city: "57",
              area: "Kalinga Nagar",
              totalRatingsString: "10000+ ratings",
              cloudinaryImageId: "fkcm08zqjevtrpy6cisj",
              cuisines: [
                "Chinese",
                "Indian",
                "Tandoor",
                "Salads",
                "Snacks",
                "Thalis",
                "South Indian",
                "Sweets",
              ],
              tags: [],
              costForTwo: 25000,
              costForTwoString: "₹250 FOR TWO",
              deliveryTime: 33,
              minDeliveryTime: 33,
              maxDeliveryTime: 33,
              slaString: "33 MINS",
              lastMileTravel: 3.5999999046325684,
              slugs: {
                restaurant: "priya-restaurant-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address: "Plot No-829 & 830/1495,Sampur,Khandagiri,Bhubaneswar",
              locality: "Sampur",
              parentId: 161363,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              ribbon: [
                {
                  type: "PROMOTED",
                },
              ],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2700,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2700,
                message: "",
                title: "Delivery Charge",
                amount: "2700",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID:
                "cid=7322371~p=1~eid=00000189-1467-4801-2668-e6aa002a011f~srvts=1688264460289",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "3.5 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "₹125 OFF",
                subHeader: "ABOVE ₹199",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "375559",
                deliveryTime: 33,
                minDeliveryTime: 33,
                maxDeliveryTime: 33,
                lastMileTravel: 3.5999999046325684,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: true,
              avgRating: "4.2",
              totalRatings: 10000,
              new: false,
            },
            subtype: "basic",
            scrubber: {
              value: "33 MINS",
            },
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "687834",
              name: "Idly Medley",
              uuid: "ef02a7dc-a268-460b-a7ae-1a1111fd9de3",
              city: "57",
              area: "Khandagiri",
              totalRatingsString: "20+ ratings",
              cloudinaryImageId: "47eabee7009164ca18a3ccf1dcc17377",
              cuisines: ["South Indian"],
              tags: [],
              costForTwo: 10000,
              costForTwoString: "₹100 FOR TWO",
              deliveryTime: 33,
              minDeliveryTime: 33,
              maxDeliveryTime: 33,
              slaString: "33 MINS",
              lastMileTravel: 1.2999999523162842,
              slugs: {
                restaurant: "idly-medley-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "ABHISHEK MOHANTY, PLOT NO-70 A, KALINGA NAGAR, LAXMI KALYAN MANDAP LANE, BHUBANESWAR, Kalinga Nagar, Ward 23, BHUBANESWAR MUNICIPAL CORPORATION, Orissa - 751019",
              locality: "Kalinga Nagar",
              parentId: 409357,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2200,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2200,
                message: "",
                title: "Delivery Charge",
                amount: "2200",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "1.2 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "15% OFF",
                subHeader: "UPTO ₹45",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "687834",
                deliveryTime: 33,
                minDeliveryTime: 33,
                maxDeliveryTime: 33,
                lastMileTravel: 1.2999999523162842,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.2",
              totalRatings: 20,
              new: false,
            },
            subtype: "basic",
            scrubber: {
              value: "33 MINS",
            },
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "568381",
              name: "Milan Restaurant",
              uuid: "666984b9-0c8c-49ab-9853-149f3a0fb9ee",
              city: "57",
              area: "Baramunda",
              totalRatingsString: "20+ ratings",
              cloudinaryImageId: "xwk19zkqddeuvvyx99sh",
              cuisines: ["Chinese", "North Indian", "Biryani", "Snacks"],
              tags: [],
              costForTwo: 25000,
              costForTwoString: "₹250 FOR TWO",
              deliveryTime: 33,
              minDeliveryTime: 33,
              maxDeliveryTime: 33,
              slaString: "33 MINS",
              lastMileTravel: 5.699999809265137,
              slugs: {
                restaurant: "milan-restaurant-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "Lane NO.1 Road NO.2, Jagannath Vihar, Baramunda, Bhubaneswar, Odisha, India - 751003",
              locality: "Jagannath Vihar",
              parentId: 136123,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 3700,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 3700,
                message: "",
                title: "Delivery Charge",
                amount: "3700",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "5.6 kms",
              hasSurge: false,
              sla: {
                restaurantId: "568381",
                deliveryTime: 33,
                minDeliveryTime: 33,
                maxDeliveryTime: 33,
                lastMileTravel: 5.699999809265137,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.1",
              totalRatings: 20,
              new: false,
            },
            subtype: "basic",
            scrubber: {
              value: "33 MINS",
            },
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "676594",
              name: "New Bengal sweets",
              uuid: "83549096-7e5e-4593-92a2-46ddf9bc2c8f",
              city: "57",
              area: "Old BBSR",
              totalRatingsString: "20+ ratings",
              cloudinaryImageId: "ad1d11521c96246a27e8f07018784f9a",
              cuisines: ["Bengali", "Sweets"],
              tags: [],
              costForTwo: 2500,
              costForTwoString: "₹25 FOR TWO",
              deliveryTime: 33,
              minDeliveryTime: 33,
              maxDeliveryTime: 33,
              slaString: "33 MINS",
              lastMileTravel: 9.399999618530273,
              slugs: {
                restaurant: "new-bengal-sweets-old-bbsr-old-bbsr-2",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "7R3F+7XP, Bhimpur, Forest Park, Bhubaneswar, Odisha 751020, India",
              locality: "Forest Park",
              parentId: 145943,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 7700,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 7700,
                message: "",
                title: "Delivery Charge",
                amount: "7700",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 1,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "9.3 kms",
              hasSurge: false,
              sla: {
                restaurantId: "676594",
                deliveryTime: 33,
                minDeliveryTime: 33,
                maxDeliveryTime: 33,
                lastMileTravel: 9.399999618530273,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "IT_IS_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.6",
              totalRatings: 20,
              new: false,
            },
            subtype: "basic",
            scrubber: {
              value: "33 MINS",
            },
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "505370",
              name: "Oven Pizza",
              uuid: "28eaaba4-24a9-48a3-9c87-f96c8458199b",
              city: "57",
              area: "Jagmohan Nagar",
              totalRatingsString: "50+ ratings",
              cloudinaryImageId: "mqdoblumklw2sxdoubam",
              cuisines: ["Pizzas", "Fast Food", "Pastas"],
              tags: [],
              costForTwo: 25000,
              costForTwoString: "₹250 FOR TWO",
              deliveryTime: 38,
              minDeliveryTime: 38,
              maxDeliveryTime: 38,
              slaString: "38 MINS",
              lastMileTravel: 6.199999809265137,
              slugs: {
                restaurant: "oven-pizza-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "Plot no-371/3033, Sahara unit no -20,  Jagamara, Bhubaneswar, Jagamara  Village, Ward 63, BHUBANESWAR  MUNICIPAL CORPORATION, Orissa -  751030",
              locality: "Jagamara Village",
              parentId: 153080,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 4200,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 4200,
                message: "",
                title: "Delivery Charge",
                amount: "4200",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 1,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "6.1 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "₹125 OFF",
                subHeader: "ABOVE ₹249",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "505370",
                deliveryTime: 38,
                minDeliveryTime: 38,
                maxDeliveryTime: 38,
                lastMileTravel: 6.199999809265137,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "IT_IS_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "3.4",
              totalRatings: 50,
              new: false,
            },
            subtype: "basic",
            scrubber: {
              value: "38 MINS",
            },
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "125317",
              name: "Maa Mangala Juice and Lassi Junction",
              uuid: "b75f7f08-2191-4807-9075-a78e1c316c81",
              city: "57",
              area: "Suryanagar",
              totalRatingsString: "1000+ ratings",
              cloudinaryImageId: "yugftcda9dxzi61nosvq",
              cuisines: ["Beverages"],
              tags: [],
              costForTwo: 10000,
              costForTwoString: "₹100 FOR TWO",
              deliveryTime: 41,
              minDeliveryTime: 41,
              maxDeliveryTime: 41,
              slaString: "41 MINS",
              lastMileTravel: 8.600000381469727,
              slugs: {
                restaurant:
                  "maa-mangala-juice-centre-ganga-nagar-unit-6-old-bbsr",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "MAA MANGALA JUICE CENTER, OLD BBSR, SHOP NO-11, RAGHUNATHA VENDINGZONE, UNIT 6,BHUBANESWER, 751006",
              locality: "Ganganagar",
              parentId: 127813,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 6200,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 6200,
                message: "",
                title: "Delivery Charge",
                amount: "6200",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 1,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "8.6 kms",
              hasSurge: false,
              sla: {
                restaurantId: "125317",
                deliveryTime: 41,
                minDeliveryTime: 41,
                maxDeliveryTime: 41,
                lastMileTravel: 8.600000381469727,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "IT_IS_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.3",
              totalRatings: 1000,
              new: false,
            },
            subtype: "basic",
            scrubber: {
              value: "41 MINS",
            },
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "583416",
              name: "Mr. Tea",
              uuid: "6d2f490e-e1d8-439b-8792-a5896fa2ba2f",
              city: "57",
              area: "Khandagiri",
              totalRatingsString: "50+ ratings",
              cloudinaryImageId: "bswbqmjy48nucazdp5zb",
              cuisines: ["Beverages"],
              tags: [],
              costForTwo: 20000,
              costForTwoString: "₹200 FOR TWO",
              deliveryTime: 42,
              minDeliveryTime: 42,
              maxDeliveryTime: 42,
              slaString: "42 MINS",
              lastMileTravel: 2.200000047683716,
              slugs: {
                restaurant: "mr.tea-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "BARAMUNDA H.B COLONY BARAMUNDA VILLAGE ,Baramunda Village,  , , , , ,,Ward 50,BHUBANESWAR MUNICIPAL CORPORATION,Orissa-751003",
              locality: "Hb Colony",
              parentId: 140417,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2200,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2200,
                message: "",
                title: "Delivery Charge",
                amount: "2200",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "2.2 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UPTO ₹50",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "583416",
                deliveryTime: 42,
                minDeliveryTime: 42,
                maxDeliveryTime: 42,
                lastMileTravel: 2.200000047683716,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.0",
              totalRatings: 50,
              new: false,
            },
            subtype: "basic",
            scrubber: {
              value: "42 MINS",
            },
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "293434",
              name: "Hotel Sri Mandira",
              uuid: "9137340d-4d1f-4268-95a4-6801b91d7dd8",
              city: "57",
              area: "Khandagiri",
              totalRatingsString: "1000+ ratings",
              cloudinaryImageId: "jk6wclvkwspqciqlqt3n",
              cuisines: ["Indian", "Chinese", "South Indian", "Sweets"],
              tags: [],
              costForTwo: 25000,
              costForTwoString: "₹250 FOR TWO",
              deliveryTime: 44,
              minDeliveryTime: 44,
              maxDeliveryTime: 44,
              slaString: "44 MINS",
              lastMileTravel: 4.300000190734863,
              slugs: {
                restaurant: "hotel-sri-mandira-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "PLOT NO-95, KHANDAGIRI TEMPLE ROAD, BHUBANESWAR, District - BHUBANESWAR MUNICIPAL CORPORATION, STATE - Orissa",
              locality: "Khandagiri Temple Road",
              parentId: 102651,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 3200,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 3200,
                message: "",
                title: "Delivery Charge",
                amount: "3200",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "4.3 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UPTO ₹50",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "293434",
                deliveryTime: 44,
                minDeliveryTime: 44,
                maxDeliveryTime: 44,
                lastMileTravel: 4.300000190734863,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "2.3",
              totalRatings: 1000,
              new: false,
            },
            subtype: "basic",
            scrubber: {
              value: "44 MINS",
            },
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "483934",
              name: "The cake&spoon",
              uuid: "ba6373d4-24ed-473c-9e9c-b791d3dc5f0f",
              city: "57",
              area: "Baramunda",
              totalRatingsString: "20+ ratings",
              cloudinaryImageId: "99be1007b270b330d57ec9e8d2e3d441",
              cuisines: ["Bakery", "Desserts"],
              tags: [],
              costForTwo: 20000,
              costForTwoString: "₹200 FOR TWO",
              deliveryTime: 47,
              minDeliveryTime: 47,
              maxDeliveryTime: 47,
              slaString: "47 MINS",
              lastMileTravel: 5.800000190734863,
              slugs: {
                restaurant: "the-cake&spoon-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "253, Alekh Ashram Ln, Millennium Colony, Baramunda, Bhubaneswar, Odisha 751003, India",
              locality: "Millennium Colony",
              parentId: 290477,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 3700,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 3700,
                message: "",
                title: "Delivery Charge",
                amount: "3700",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "5.8 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "₹100 OFF",
                subHeader: "ABOVE ₹399",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "483934",
                deliveryTime: 47,
                minDeliveryTime: 47,
                maxDeliveryTime: 47,
                lastMileTravel: 5.800000190734863,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "3.5",
              totalRatings: 20,
              new: false,
            },
            subtype: "basic",
            scrubber: {
              value: "47 MINS",
            },
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "507072",
              name: "Foods Healu",
              uuid: "f696e076-e84d-48dc-9ec7-02478f5e5e9d",
              city: "57",
              area: "Jagmohan Nagar",
              totalRatingsString: "500+ ratings",
              cloudinaryImageId: "gbptifdys2nopdjb7qgl",
              cuisines: ["Indian", "Healthy Food"],
              tags: [],
              costForTwo: 20000,
              costForTwoString: "₹200 FOR TWO",
              deliveryTime: 48,
              minDeliveryTime: 48,
              maxDeliveryTime: 48,
              slaString: "48 MINS",
              lastMileTravel: 5,
              slugs: {
                restaurant: "foods-healu-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "Plot No.-1249/5059, Lane No. 2C, Mallick Complex, Jagamara Khandagiri, Jagamara, Bhubaneswar, Odisha 751030, India",
              locality: "Mallick complex",
              parentId: 303393,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 3700,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 3700,
                message: "",
                title: "Delivery Charge",
                amount: "3700",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "5 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "50% OFF",
                subHeader: "",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "507072",
                deliveryTime: 48,
                minDeliveryTime: 48,
                maxDeliveryTime: 48,
                lastMileTravel: 5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "--",
              totalRatings: 500,
              new: false,
            },
            subtype: "basic",
            scrubber: {
              value: "48 MINS",
            },
          },
        ],
        totalRestaurants: 99,
      },
      subtype: "personalized",
    },
    parentWidget: false,
  },
];
